version: "3.7"

services:
  kratos-migrate:
    image: oryd/kratos:v0.10.1
    depends_on:
      - postgres
    environment:
      - DSN=postgres://kratos:secret@postgres:5432/kratos?sslmode=disable&max_conns=20&max_idle_conns=4
    command: -c /etc/config/kratos/kratos.yml migrate sql -e --yes
    restart: on-failure
    volumes:
      - type: bind
        source: ./dev/kratos.yml
        target: /etc/config/kratos/kratos.yml
      - type: bind
        source: ./dev/email-schema.json
        target: /etc/config/kratos/identity.schema.json
    networks:
      - intranet

  kratos:
    image: oryd/kratos:v0.10.1
    command: serve -c /etc/config/kratos/kratos.yml --dev --watch-courier
    depends_on:
      - postgres
    volumes:
      - type: bind
        source: ./dev/kratos.yml
        target: /etc/config/kratos/kratos.yml
      - type: bind
        source: ./dev/email-schema.json
        target: /etc/config/kratos/identity.schema.json
    environment:
      - DSN=postgres://kratos:secret@postgres:5432/kratos?sslmode=disable&max_conns=20&max_idle_conns=4
    ports:
      - "4433:4433" # public
      - "4434:4434" # admin
    networks:
      - intranet

  postgres:
    image: postgres:9.6
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_USER=kratos
      - POSTGRES_PASSWORD=secret
      - POSTGRES_DB=kratos
    networks:
      - intranet

  mailslurper:
    image: oryd/mailslurper:latest-smtps
    ports:
      - "4436:4436"
      - "4437:4437"
    networks:
      - intranet

networks:
  intranet:
