#!/bin/bash

echo "\
NODE_PATH=${NODE_PATH}
NODE_ENV=${NODE_ENV}
SESSION_KEYS=${SESSION_KEYS}
HOST=${HOST}
PORT=${PORT}
WALLET_NAME=${WALLET_NAME}
WALLET_LAYOUT=${WALLET_LAYOUT}
WALLET_THEME=${WALLET_THEME}
SUPPORT_EMAIL=${SUPPORT_EMAIL}
SHARE_URI=${SHARE_URI}
NETWORK=${NETWORK}
GRAPHQL_URI=${GRAPHQL_URI}
GRAPHQL_SUBSCRIPTION_URI=${GRAPHQL_SUBSCRIPTION_URI}
AUTH_ENDPOINT=${AUTH_ENDPOINT}
KRATOS_API_URL=${KRATOS_API_URL}
KRATOS_BROWSER_URL=${KRATOS_BROWSER_URL}
GALOY_AUTH_ENDPOINT=${GALOY_AUTH_ENDPOINT}
KRATOS_FEATURE_FLAG=${KRATOS_FEATURE_FLAG}
" | tee .env
