name: "Tests"

on:
  pull_request:
    branches: [main]

jobs:
  integration:
    name: Tests
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - run: yarn install
      - name: Run all tests
        run: yarn test
